apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: loki
          image: {{ .Values.images.loki }}
          args:
            - -config.file=/etc/loki/local-config.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki/
            - name: loki-storage
              mountPath: /loki
            - name: loki-wal
              mountPath: /wal
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: loki-storage
          emptyDir: {}
        - name: loki-wal
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
