{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATA_SOURCE_NAME: {{ .Values.postgres.dataSourceName | quote }}
{{- end }}
