apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-db
  namespace: student-api
  labels:
    app: student-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-db
  template:
    metadata:
      labels:
        app: student-db
    spec:
      nodeSelector:
        type: database
      containers:
        - name: student-db
          image: postgres:16
          envFrom:
            - secretRef:
                name: student-db-credentials
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: student-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: student-db-data
          persistentVolumeClaim:
            claimName: student-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-db-pvc
  namespace: student-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: student-db
  namespace: student-api
  labels:
    app: student-db
spec:
  type: ClusterIP
  selector:
    app: student-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres